#
#
# Warnning use ' for string not " if you want to use deploy.sh
SubAddresses = ['cf-us1.libragen.cn:443', 'n-us1.chainese.us.kg:80'] # hosts for generate vless URL
ListenAddr = '0.0.0.0:80' # websocket server listen address
RegisterUrl = 'https://admin.cf.workers.cn/api/nodes' #the master admin server for user auth,data traffic. can be empty if you only want to use the node for stand alone
RegisterToken = 'unchain.people.from.censorship.and.surveillance'# can be empty string if you only want to use the node for yourself
AllowUsers = '' # UUID string eg. '6fe57e3f-e618-4873-ba96-a76adec22ccd,6fe57e3f-e618-4873-ba96-a76adec22cce'  can not be empty if you want to use the node for yourself in standalone mode
LogFile = 'unchain.log' # can be empty if you don't want to log to file, so the log will be print to stdout
DebugLevel = 'debug' # debug, info, warn, error